[build]
  command = "npx prisma generate && npx prisma db push && next build"
  publish = ".next"

[build.environment]
  DATABASE_URL = "postgresql://neondb_owner:npg_kNRDpCJaUT56@ep-divine-feather-ayoo2w6d-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

[[plugins]]
  package = "@netlify/plugin-nextjs"
